[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
agent_registry = "CQZEo9zd8QNgT2uUJRn1cdHxc2794xFumQu9ZXL4Syk8"

[programs.devnet]
agent_registry = "CQZEo9zd8QNgT2uUJRn1cdHxc2794xFumQu9ZXL4Syk8"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
